# -*- coding: utf-8 -*-
"""Copy of data visualization tool.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Axdv80hvElBxOQxBHP0cDig7KPm_qZ1S
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Data for plotting
data = {
    'Fruits': ['Apples', 'Bananas', 'Cherries', 'Dates'],
    'Quantity': [20, 30, 15, 10]
}

df = pd.DataFrame(data)

# Bar chart using Matplotlib
plt.bar(df['Fruits'], df['Quantity'])
plt.title('Quantity of Fruits')
plt.xlabel('Fruit')
plt.ylabel('Quantity')
plt.show()

# Heatmap using Seaborn
data = {
    'Apples': [35, 40, 25],
    'Bananas': [21, 34, 27],
    'Cherries': [15, 30, 25],
    'Dates': [10, 15, 20]
}
df2 = pd.DataFrame(data, index=['Store1', 'Store2', 'Store3'])

# Create heatmap
sns.heatmap(df2, annot=True, cmap="YlGnBu")
plt.show()